### PR TITLE
Show datasources which have not yet published to deep storage in coordinator console sidebar

### PR DESCRIPTION
**Pull request by clintropolis**
Solves https://github.com/apache/incubator-druid/issues/4715 by combining output of `/druid/coordinator/v1/metadata/datasources` and `/druid/coordinator/v1/datasources`. I ... think this is correct, it works as expected when debugging locally at least. I feel like this promise chain could be nicer, but this stuff is pretty old and I don't know how modern I can go...

Unpublished datasources will appear with a green indicator as follows:
screen shot 2018-10-01 at 5 42 40 pm

screen shot 2018-10-01 at 5 42 49 pm

screen shot 2018-10-01 at 6 15 24 pm

### CODE REVIEW

**Comment by clintropolis** [comment]
Added distinct styling to datasources which are not yet persisted to deep storage 
screen shot 2018-10-01 at 5 48 41 pm

screen shot 2018-10-01 at 5 42 49 pm

**Comment by clintropolis** [comment]
oops, legend was wrong, fixed
screen shot 2018-10-01 at 6 15 24 pm

**Comment by evasomething** [comment]
this looks good to me though I'm not that familiar with the console/coffeescript. 
as points of curiosity, does loadStatus <=0 necessarily mean indexing is happening?

also, did anything in this need the updated jquery version? or just for properness?

**Comment by clintropolis** [comment]
[This code](https://github.com/druid-io/druid-console/pull/21/files#diff-6fc8ec275aacf6de310248a794363d91R73) is setting `loadStatus` to be `-1` explicitly if `loadStatuses` does not contain the datasource, which should only happen if it's only available at `/datasources` without the corresponding `/metadata/datasources` entry [(retrieved here)](https://github.com/druid-io/druid-console/pull/21/files#diff-499fa1ace9c20ed739020e9d0b9581afR49).

I think the jquery version update was just an unintended side-effect of rebuilding the package because of bower or .. something, but everything seemed to still operate correctly. I didn't actually notice until you pointed it out heh, but I suspect some other versions probably slightly changed too.

**Comment by dclim** [comment]
👍

**Comment by evasomething** [comment]
👍

**Pull request merged**
