### PR TITLE
Package the Druid console as a maven artifact

### PR DESCRIPTION
**Pull request by xvrl**
`mvn package` now takes care of everything, no pre-requisites required, no need to install node anymore

### CODE REVIEW

**Comment by fjy** [comment]
:+1:

**Comment by drcrallen** [comment]
I had to do the following:
`npm install node-sass`

Then I got `bower                       EMALFORMED Failed to read /Users/charlesallen/src/druid-console/bower_components/jQuery/.bower.json`

**Comment by xvrl** [comment]
@drcrallen there is a bug in the maven-frontend-plugin right now, so make sure you have no other npm, node, or anything related on your path.

Sometimes the bower install step fails when it runs a second, time, when that happens, just do maven clean package

**Comment by drcrallen** [comment]
`[INFO] BUILD SUCCESS`

**Pull request merged**
